<a href="https://colab.research.google.com/github/infantry97/open-source-cs/blob/master/zillow_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import os
os.getcwd #tells you what dir you're working in, if you happen to be running python on your laptop

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
pd.read_csv('/content/dataFiles/results2.csv')

    RegionID                      RegionName  ... ForecastYChange  CurrentYChange
0     394913                        New York  ...        0.024815        0.016822
1     753899  Los Angeles-Long Beach-Anaheim  ...        0.018667        0.017836
2     394463                         Chicago  ...        0.006289        0.012094
3     394514               Dallas-Fort Worth  ...        0.032765        0.022331
4     394974                    Philadelphia  ...        0.021080        0.031951
5     394692                         Houston  ...        0.018545        0.008633
6     395209                      Washington  ...        0.017180        0.023268
7     394856           Miami-Fort Lauderdale  ...        0.018888        0.007613
8     394347                         Atlanta  ...        0.067476        0.047350
9     394404                          Boston  ...        0.020851        0.028897
10    395057                   San Francisco  ...        0.013457        0.005153
11    394532                         Detroit  ...        0.022351        0.015980
12    395025                       Riverside  ...        0.032956        0.031881
13    394976                         Phoenix  ...        0.063830        0.079259
14    395078                         Seattle  ...        0.032577        0.024267
15    394865             Minneapolis-St Paul  ...        0.038537        0.034459
16    395056                       San Diego  ...        0.048847        0.041938
17    395121                       St. Louis  ...        0.061420        0.050403
18    395148                           Tampa  ...        0.053103        0.051487
19    394358                       Baltimore  ...        0.026038        0.008755
20    394530                          Denver  ...        0.056667        0.027984
21    394982                      Pittsburgh  ...        0.068085        0.070128
22    394998                        Portland  ...        0.036116        0.026748
23    394458                       Charlotte  ...        0.030103        0.053364
24    395045                      Sacramento  ...        0.049808        0.044597
25    395055                     San Antonio  ...        0.026851        0.013190
26    394943                         Orlando  ...        0.039148        0.044476
27    394466                      Cincinnati  ...        0.078773        0.056968
28    394475                       Cleveland  ...        0.014071        0.018147
29    394735                     Kansas City  ...        0.042179        0.032668
30    394775                       Las Vegas  ...        0.029477        0.056854
31    394492                        Columbus  ...        0.031145       -0.001681
32    394705                    Indianapolis  ...        0.017226        0.027959
33    395059                        San Jose  ...        0.012439        0.003349
34    394355                          Austin  ...        0.043505        0.048170
35    395194                  Virginia Beach  ...        0.036630        0.024775
36    394902                       Nashville  ...        0.055102        0.030856
37    395005                      Providence  ...        0.022603        0.031802
38    394862                       Milwaukee  ...        0.037975        0.027881
39    394714                    Jacksonville  ...        0.022611        0.041793
40    394849                         Memphis  ...        0.105805        0.039922
41    394935                   Oklahoma City  ...        0.012605        0.022556
42    394807     Louisville-Jefferson County  ...        0.019143        0.040797
43    394669                        Hartford  ...        0.005267       -0.001503
44    395022                        Richmond  ...        0.029652        0.034509
45    394910                     New Orleans  ...        0.136064        0.054784
46    394425                         Buffalo  ...       -0.005000       -0.008920
47    395012                         Raleigh  ...        0.031988        0.033858
48    394388                      Birmingham  ...        0.026902        0.032567
49    395053                  Salt Lake City  ...        0.027591        0.013643

[50 rows x 7 columns]

In [0]:
data = pd.read_csv('/content/dataFiles/results2.csv')

In [0]:
data.to_csv('/content/dataFiles/zillow.csv') #this is how to export pandas dataframes to files